### ISSUE TITLE
Container not reachable from host

### ISSUE THREAD

**Issue by stimon** [bertvannuffelen/docker-ontop#1]
Hi!

I am trying to run the docker container you generously made available for Ontop on OSX, without much success.

The thing is that the container seems to be up, but tomcat is only reachable from inside the container.

```
$ docker run -p 8080:8080 --name ontop-webapp -v $mydir/data:/data tenforce/docker-ontop
Archive:  ontop.zip
  inflating: openrdf-sesame.war      
  inflating: openrdf-workbench.war  

+ echo deploy the configuration files
+ service tomcat7 stop
deploy the configuration files
Stopping Tomcat servlet engine: tomcat7 (not running).
+ [ -f /config/init.sh ]
+ echo Running custom init script
+ chmod +x /config/init.sh
Running custom init script
+ sync
+ /config/init.sh
WARNING: missing Microsoft JDBC driver
See https://msdn.microsoft.com/en-us/library/mt683464%28v=sql.110%29.aspx
+ [ -n  ]
+ [ -n  ]
+ [ -n /usr/lib/jvm/java-8-openjdk-amd64/jre ]
+ echo Adding JAVA_HOME
+ echo JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64/jre"
Adding JAVA_HOME
deploy the configuration files
+ echo deploy the configuration files
+ chown tomcat7:tomcat7 /config
+ cp /config/tomcat-setenv.sh /usr/share/tomcat7/bin/setenv.sh
+ cp /config/tomcat-users.xml /var/lib/tomcat7/conf/tomcat-users.xml
+ chown root:tomcat7 /var/lib/tomcat7/conf/tomcat-users.xml
+ cp /contexts/example.xml /contexts/openrdf-sesame.xml /contexts/openrdf-workbench.xml /etc/tomcat7/Catalina/localhost/
+ echo Start the tomcat7 service
+ service tomcat7 start
Start the tomcat7 service
Starting Tomcat servlet engine: tomcat7 failed!
+ echo alias exit="echo Are you sure? this will kill the container. use Ctrl + p, Ctrl + q to detach or ctrl + d to exit"
+ tail -f /var/log/tomcat7/catalina.out
Nov 15, 2016 11:35:19 AM org.apache.catalina.startup.HostConfig deployDescriptor
INFO: Deployment of configuration descriptor /etc/tomcat7/Catalina/localhost/host-manager.xml has finished in 28 ms
Nov 15, 2016 11:35:19 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory /var/lib/tomcat7/webapps/ROOT
Nov 15, 2016 11:35:19 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory /var/lib/tomcat7/webapps/ROOT has finished in 83 ms
Nov 15, 2016 11:35:19 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8080"]
Nov 15, 2016 11:35:19 AM org.apache.catalina.startup.Catalina start
INFO: Server startup in 3227 ms
```

```
$ docker-machine ip
192.168.99.100
$ curl 192.168.99.100:8080
curl: (7) Failed to connect to 192.168.99.100 port 8080: Connection refused
$ docker exec -it ontop-webapp sh
# curl localhost:8080
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>Apache Tomcat</title>
</head>
<body>
<h1>It works !</h1>
<p>If you're seeing this page via a web browser, it means you've setup Tomcat successfully. Congratulations!</p>
 
<p>This is the default Tomcat home page. It can be found on the local filesystem at: <code>/var/lib/tomcat7/webapps/ROOT/index.html</code></p>
<p>Tomcat7 veterans might be pleased to learn that this system instance of Tomcat is installed with <code>CATALINA_HOME</code> in <code>/usr/share/tomcat7</code> and <code>CATALINA_BASE</code> in <code>/var/lib/tomcat7</code>, following the rules from <code>/usr/share/doc/tomcat7-common/RUNNING.txt.gz</code>.</p>
<p>You might consider installing the following packages, if you haven't already done so:</p>
<p><b>tomcat7-docs</b>: This package installs a web application that allows to browse the Tomcat 7 documentation locally. Once installed, you can access it by clicking <a href="docs/">here</a>.</p>
<p><b>tomcat7-examples</b>: This package installs a web application that allows to access the Tomcat 7 Servlet and JSP examples. Once installed, you can access it by clicking <a href="examples/">here</a>.</p>
<p><b>tomcat7-admin</b>: This package installs two web applications that can help managing this Tomcat instance. Once installed, you can access the <a href="manager/html">manager webapp</a> and the <a href="host-manager/html">host-manager webapp</a>.<p>
<p>NOTE: For security reasons, using the manager webapp is restricted to users with role "manager-gui". The host-manager webapp is restricted to users with role "admin-gui". Users are defined in <code>/etc/tomcat7/tomcat-users.xml</code>.</p>
</body>
</html>
# 
```
I'm still very new to docker, but I think the configuration looks fine

```
$ docker ps
CONTAINER ID        IMAGE                   COMMAND              CREATED             STATUS              PORTS                              NAMES
19050e7487f0        tenforce/docker-ontop   "/myconfig/run.sh"   16 minutes ago      Up 16 minutes       1433/tcp, 0.0.0.0:8080->8080/tcp   ontop-webapp
```

As far as I know, ontop should be reachable at http://192.168.99.100:8080/openrdf-workbench

Tomcat logs some errors, but I don't look related and it still serves ROOT:
```
# cat /var/log/tomcat7/catalina.out
Nov 15, 2016 11:35:15 AM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat7/common/classes], exists: [false], isDirectory: [false], canRead: [false]
Nov 15, 2016 11:35:15 AM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat7/common], exists: [false], isDirectory: [false], canRead: [false]
Nov 15, 2016 11:35:15 AM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat7/server/classes], exists: [false], isDirectory: [false], canRead: [false]
Nov 15, 2016 11:35:15 AM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat7/server], exists: [false], isDirectory: [false], canRead: [false]
Nov 15, 2016 11:35:15 AM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat7/shared/classes], exists: [false], isDirectory: [false], canRead: [false]
Nov 15, 2016 11:35:15 AM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat7/shared], exists: [false], isDirectory: [false], canRead: [false]
Nov 15, 2016 11:35:16 AM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-bio-8080"]
Nov 15, 2016 11:35:16 AM org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 264 ms
Nov 15, 2016 11:35:16 AM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Catalina
Nov 15, 2016 11:35:16 AM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.56 (Debian)
Nov 15, 2016 11:35:16 AM org.apache.catalina.startup.HostConfig deployDescriptor
INFO: Deploying configuration descriptor /etc/tomcat7/Catalina/localhost/openrdf-workbench.xml
Nov 15, 2016 11:35:17 AM org.apache.catalina.startup.HostConfig deployDescriptor
INFO: Deployment of configuration descriptor /etc/tomcat7/Catalina/localhost/openrdf-workbench.xml has finished in 1,292 ms
Nov 15, 2016 11:35:17 AM org.apache.catalina.startup.HostConfig deployDescriptor
INFO: Deploying configuration descriptor /etc/tomcat7/Catalina/localhost/openrdf-sesame.xml
Nov 15, 2016 11:35:19 AM org.apache.catalina.startup.HostConfig deployDescriptor
INFO: Deployment of configuration descriptor /etc/tomcat7/Catalina/localhost/openrdf-sesame.xml has finished in 1,751 ms
Nov 15, 2016 11:35:19 AM org.apache.catalina.startup.HostConfig deployDescriptor
INFO: Deploying configuration descriptor /etc/tomcat7/Catalina/localhost/example.xml
Nov 15, 2016 11:35:19 AM org.apache.catalina.startup.ContextConfig beforeStart
SEVERE: Exception fixing docBase for context [/example]
java.io.FileNotFoundException: /webapps/example-1.2.war (No such file or directory)
at java.util.zip.ZipFile.open(Native Method)
at java.util.zip.ZipFile.<init>(ZipFile.java:219)
at java.util.zip.ZipFile.<init>(ZipFile.java:149)
at java.util.jar.JarFile.<init>(JarFile.java:166)
at java.util.jar.JarFile.<init>(JarFile.java:103)
at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:99)
at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
at sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:89)
at org.apache.catalina.startup.ExpandWar.expand(ExpandWar.java:111)
at org.apache.catalina.startup.ContextConfig.fixDocBase(ContextConfig.java:735)
at org.apache.catalina.startup.ContextConfig.beforeStart(ContextConfig.java:863)
at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:388)
at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:402)
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:672)
at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1861)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Nov 15, 2016 11:35:19 AM org.apache.catalina.core.StandardContext resourcesStart
SEVERE: Error starting static Resources
java.lang.IllegalArgumentException: Invalid or unreadable WAR file : /webapps/example-1.2.war
at org.apache.naming.resources.WARDirContext.setDocBase(WARDirContext.java:131)
at org.apache.catalina.core.StandardContext.resourcesStart(StandardContext.java:5143)
at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5327)
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:672)
at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1861)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Nov 15, 2016 11:35:19 AM org.apache.catalina.core.ContainerBase addChildInternal
SEVERE: ContainerBase.addChild: start: 
org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/example]]
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:672)
at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1861)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.catalina.LifecycleException: Error in resourceStart()
at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5328)
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
... 10 more
Nov 15, 2016 11:35:19 AM org.apache.catalina.startup.HostConfig deployDescriptor
SEVERE: Error deploying configuration descriptor /etc/tomcat7/Catalina/localhost/example.xml
java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/example]]
at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:904)
at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:672)
at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1861)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Nov 15, 2016 11:35:19 AM org.apache.catalina.startup.HostConfig deployDescriptor
INFO: Deployment of configuration descriptor /etc/tomcat7/Catalina/localhost/example.xml has finished in 7 ms
Nov 15, 2016 11:35:19 AM org.apache.catalina.startup.HostConfig deployDescriptor
INFO: Deploying configuration descriptor /etc/tomcat7/Catalina/localhost/manager.xml
Nov 15, 2016 11:35:19 AM org.apache.catalina.startup.HostConfig deployDescriptor
INFO: Deployment of configuration descriptor /etc/tomcat7/Catalina/localhost/manager.xml has finished in 21 ms
Nov 15, 2016 11:35:19 AM org.apache.catalina.startup.HostConfig deployDescriptor
INFO: Deploying configuration descriptor /etc/tomcat7/Catalina/localhost/host-manager.xml
Nov 15, 2016 11:35:19 AM org.apache.catalina.startup.HostConfig deployDescriptor
INFO: Deployment of configuration descriptor /etc/tomcat7/Catalina/localhost/host-manager.xml has finished in 28 ms
Nov 15, 2016 11:35:19 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory /var/lib/tomcat7/webapps/ROOT
Nov 15, 2016 11:35:19 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory /var/lib/tomcat7/webapps/ROOT has finished in 83 ms
Nov 15, 2016 11:35:19 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8080"]
Nov 15, 2016 11:35:19 AM org.apache.catalina.startup.Catalina start
INFO: Server startup in 3227 ms
```

I bet it must be some issue with my local docker config, but I'm already without clues.
I'm using latest docker relase for Mac OSX (Version 1.12.3).

Thanks in advance.
Santi

**Comment by stimon** [comment]
I'm sorry, I found out it is a OSX issue with docker (https://github.com/docker/docker/issues/20016). 
As noted in https://github.com/docker/docker/issues/20016#issuecomment-228056188 the solution is to explicitly configure port forwarding rules in virtualbox config.
Go to settings -> network -> port forwarding. Add one rule for each port you want to be forwarded from host to guest OS.
